language: java
sudo: required
jdk:
- oraclejdk8
branches:
  only:
  - develop
deploy:
  provider: heroku
  app:
    develop: jees-quoridor-backend
  api_key:
    secure: Qn5IfGU0NW713CinT9KXOA0/oyojdso0s2fh5oC79gVJHdTyx5utsqaKlcthniE0JVRaTe09iIR+yxND8IR0ssFBvEXdiAkAXKHt/Ix3V8hBRNZA+EuNy3SPHV/tZ7x+4+NmxaDPKn1pP3kC2CRVvLrDOoKQjxtsgy7O816RdN22qqXYLh8tcvREM55ihWKgBBboql6n2eD5w/6WI5dMxegd/nEw5aniZoPgcqGQOS5Uzx/ojj/79eMgTlofxtOQW3x2gSQBTNbSFvRjNWrbaIkrPJczcht5XfqVdWXiyVE9wTvd+IDDMln0MfcU2CdI56jcwAel202Ph2GT/klihQiRj/4z0c8vSYiie6K+LgaM3eVzpxXBhX8zZ+ZEWxBzzaMmJpPmG2pNd6dK36wUwza1fMtkPvDDCpWdReuI5/m1agy9pvvGF1rBw833Q3dYZav5F6vAqxFbcO6s0LdlxQBhcwc97kywnTdcRt4WpZhP/vQhWhpWqT/NDk7onTe8t6X3yKWtTZ0rfVWPqfc5MPrwFrTG7XwS4BvfFb8t/lawrGc9BDbsOyqkb6shV++spaYoOYu+SuHrEdDNPvRVUAjcgMQFygGFky90iZwfJ2kkMuLL6S9MpYl9I/td1fNcqzYPi4++u2X1jbAkEe9l3P8n/ZXngMEM1wjMbzbX3Xs=
